namespace = "GyDX55sFnbr9yCB-mPyXsy4kAUPUY8ftpWX62s6UcnvfIQ=="
local_channels = ['uPMU_4/L1','uPMU_4/L2','uPMU_4/L3']
reference_channels = ['uPMU_0/L1','uPMU_0/L2','uPMU_0/L3']
entity = 'lpbc_4.ent'
wavemq = '127.0.0.1:4516'
rate = 8  # number of seconds between calls to 'step'
name = 'lpbc_671' # node ID
spbc = 'spbc-jasper-1'
